name: github pages

on:
  push:
    branches:
      - master
      - fix_sphinx

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "sphinx"
          build-command: |
            poetry run python3 -m pip install -r sphinx/requirements.txt
            poetry run sphinx-apidoc -f -o ./sphinx femio
            poetry run sphinx-build ./sphinx ./docs
            poetry build
            cp -r docs public
            mv dist/*.whl public/
      - name: deploy_pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          force_orphan: true
